### ISSUE TITLE
Need to define the expected behaviour when a tile is removed by swiping gesture

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#109]
We would need to define what should happen once a tile is removed.
Currently what seems to happen is:
If a tile is removed and you refresh the page, it is not loaded.
If the app is closed and open again, then the tile apperas again

If all the tiles are removed _Nothing found_ screen is shown, but that is not actually true as the beacons are there and can be found by other apps or after closing the app and opening it again

So that we can verify that the functionality is working correctly we would need to define the expected behaviour in each possible case.

**Comment by wilsonpage** [comment]
This feature is half implemented. What we have now is just the UI part. Once completely finished the expected behaviour will look like:
- Tile is swiped away
- Tile moves to 'hidden tiles' list below main list
- When app is rebooted or list is refreshed any dismissed tiles will be in the 'hidden tiles' list.

See issue #86 for a little more detail.

**Comment by wilsonpage** [comment]
- Tapping a tile in the 'hidden tiles' list will ask user if they want to 'unblock' this tile.
- Upon 'yes', the tile will move up into the the primary tile list.

**Comment by isabelrios** [comment]
Understood!Thanks for the explanation!
Will check that issue 86

**Comment by isabelrios** [comment]
This issue does not make sense with the current implementation. Closing...
