### ISSUE TITLE
Investigate Testfairy for android

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-client#56]

**Comment by isabelrios** [comment]
Meeting scheduled on May 9th at 4pm CET for asking questions to TestFairy team

**Comment by wilsonpage** [comment]
REPOST from @isabelrios:

This is a quick summary of what I learnt about TestFairy.
- In order to get the information from the app on TestFairy dashboard it is neccesary to include an sdk in the app:
  - http://docs.testfairy.com/Android/Integrating_Android_SDK.html
  - The info that would be available is: screenshots and video recordings, logs, metrics (for example, CPU and memory performance and more: https://app6.testfairy.com/projects/50-groupshot/builds/4461/sessions/17/?accessToken=C7fplNuETC94Sd89RrkRm2aarfQ#t=0m35s
- App can be sent by email, individually or to a group. It can also be shared to recruite testers via Facebook or twitter or sharing a link somehow
- It allows integration with Bugzilla, Jira, Github issues for bugs
- Once a bug is open from the tool it attaches the image, logs, video so all the info is presented in order to debug the issue
- Crash and feedback reports, this is now integrated with hipchat to receive instant notifications and could be also integrated with irc if we are interested. Crashes are sent automatically and can be checked on the dashboard. Feedback can be received by email too
- Searches for users patterns when using the app, for example, look for users that used the app less than 5 seconds. There would probably an issue there and can be checked by looking at the user session
- Once you open an user session, all the steps he did inside the app are recorded so it is possible to see the performance of the app while it is being used
- It would be possible to use Travis-CI for uploading builds automatically

There is a regular account and an entreprise one which, as you can imagine, is not for free. Some of the limitations would be the integration with irc, having several admins to manage one app dashboard.

I think in general it looks good and would be really useful to have many testers using the app in different android devices with beacons with different urls. But we should have to modify the app for including the sdk.

What do you think, would it be worthy to give it a try?

Thanks,
Isabel

**Comment by wilsonpage** [comment]
REPOST @isabelrios:

There is a regular account and an entreprise one which, as you can imagine, is not for free. Some of the limitations would be the integration with irc, having several admins to manage one app dashboard.

I think in general it looks good and would be really useful to have many testers using the app in different android devices with beacons with different urls. But we should have to modify the app for including the sdk.

**Comment by isabelrios** [comment]
So, in theory, these are the only necessary changes to the app so that we can see the activity on TestFairy:
_First change_: Add the SDK to your build.gradle
  _dependencies {
      compile 'testfairy:testfairy-android-sdk:1.+@aar'
  }_
make sure you have jcenter() repository included.

_Second change_: Add Testfairy to your main activity's onCreate:
_import com.testfairy.TestFairy;
  public class MainActivity extends Activity {
   @Override
    public void onCreate() {
       TestFairy.begin(this, YOUR_APP_TOKEN);
   }_

_Third change_: Logs - _android.permission.READ_LOGS_ (Optional)

I created this branch [1] and make the modifications:
_First change_: In android/app/build.gradle file

_Second change_: I tried to add it to MainAcitivity.java file but then the build does not compile.
So, Looks like having created the app using native-react this has to be done in a different way than how it is described in the instructions. I added that code into this file: magnet-client/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java under the 'onCreate' that is there. But I guess this is not correct.

_Third change_: In android/app/src/main/AndroidManifest.xml

The app compiles and I get the app-debug.apk file but there is something wrong with the changes since they seems to be ignored by the testFairy tool and nothing regarding the app is shown in the dashboard. 
I am sorry I do not know much about the app and maybe it is not that easy to add those changes or they are in the wrong place. Could you please help me to find out where I should make those changes? @arcturus, @wilsonpage 

Thank you in advance!

[1]https://github.com/isabelrios/magnet-client/tree/adding-android-sdk

**Comment by isabelrios** [comment]
Some update here although no big progress :S
I know why the app is not loaded in TestFairy, the changes to add its code in 'onCreate' method are not kept after creating the .apk. So the TestFaire sdk is not correclty set and working.

I made those changes [1] in ReactActivity[2]. I firstly removed the node-modules folder and did a npm install after the changes. Then I run 'react-native run-android' to get the .app-debug.apk. This is created correctly but I extracted the content to check it and there, the changes done in ReactActivity do not appear.

I should be missing or doing something wrongly. Will keep investigating. Please let me know if you have any idea about where the problem could be. 
Thanks!

[1] Add Testfairy to your main activity's onCreate:
import com.testfairy.TestFairy;
public class MainActivity extends Activity {
@Override
public void onCreate() {
TestFairy.begin(this, YOUR_APP_TOKEN);
}
[2] ~magnet-client/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java

**Comment by isabelrios** [comment]
Good news on this. Finally the changes made on the app are working and it can be seen on the dashboard. 
The app can be shared by email and once the user installs it, the use of the app is recorded and seen on the dashboard. As a user is possible to send feedback and it is also shown on the dashboard. 

For the testing I used a debug build, but we would need to create a release build with the changes to upload and start sharing with more people.

**Comment by isabelrios** [comment]
This is an example of the use of the app that can be seen on the dashboard:

https://app.testfairy.com/projects/2673947-magnet/builds/3540878/sessions/9/?accessToken=69TUoWM6edQBmU5nMCWuY-yaDQ8

**Comment by isabelrios** [comment]
The investigation has been done. Closing this issue and opening a new one with the new needs in case we want to continue with this.
https://github.com/mozilla-magnet/magnet-client/issues/119

Thanks!
